#!/bin/bash

echo 2048 > /sys/class/rtc/rtc0/max_user_freq
echo 2048 > /proc/sys/dev/hpet/max-user-freq
setpci -v -d *:* latency_timer=b0
setpci -v -s 0c:00.1 latency_timer=ff
cpupower frequency-set -g performance
