#!/bin/bash

DATE=`date +"%Y-%m-%d"`
NOTE_FILE_NAME=$HOME/Documents/Notes/notes-${DATE}.md

if [ ! -f $NOTE_FILE_NAME ]; then
    echo "# Notes for ${DATE}" > ${NOTE_FILE_NAME} 
fi

nvim -c "norm Go" -c "norm Go## $(date +%H:%M)" \
     -c "norm G2o" -c "norm zz" -c "startinsert" ${NOTE_FILE_NAME}
     
