#!/bin/bash

for file in * ; do 
    mv -n "$file" "$(echo "$file" | sed -e 's/\ /_/g')"
done

for file in * ; do 
    mv -n "$file" "$(echo "$file" | sed -e 's/_-_/-/g')"
done 

for file in * ; do 
    mv -n "$file" "$(echo "$file" | sed -e 's/,//g')"
done    
