#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.
# Show 🔒 if a vpn connection is active

#case $BLOCK_BUTTON in
#	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
#	3) notify-send "🌐 Internet module" "\- Click to connect
#睊: no wifi connection
# : wifi connection with quality
# : no ethernet
# : ethernet working
#嬨: vpn is active
#" ;;
#	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifiicon="^c#d79921^睊 " ;;
	up) wifiicon="$(awk '/^\s*w/ { print "^c#d79921^^c#ebdbb2^",  int($3 * 100 / 70) "% " }' /proc/net/wireless)" ;;
esac

printf "%s%s%s\n" "$wifiicon" "$(sed "s/down/^c#d7992^/;s/up/^c#d79921^/" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/嬨/" /sys/class/net/tun*/operstate 2>/dev/null)"
