#!/bin/bash

source $HOME/.themes/statusbar_colors.sh

ICON=
BAR_BG_COLOR="^b"$DARK_BACKGROUND"^"
BG_COLOR="^b"$BLUE_LIGHT"^"
ICON_BG_COLOR="^b"$BLUE_DARK"^"
ICON_COLOR="^c"$DARK_BACKGROUND"^"
TEXT_COLOR="^c"$DARK_BACKGROUND"^"
ARROW_COLOR="^c"$BLUE_DARK"^"
ARROW='\ue0b2'
POWERLINE_COLOR="^c"$BLUE_DARK"^"
POWERLINE_COLOR_2="^c"$BLUE_LIGHT"^"
LEFT_ARROW='\ue0b2'
LEFT_ROUND='\ue0b6'
RIGHT_ROUND='\ue0b4'

echo -e $POWERLINE_COLOR$LEFT_ROUND$ICON_BG_COLOR$ICON_COLOR$ICON $BG_COLOR$TEXT_COLOR"$(date '+%d %B %Y')"$BAR_BG_COLOR$POWERLINE_COLOR_2$RIGHT_ROUND

case $BLOCK_BUTTON in
    1) st -e calcurse;;
esac
