#!/bin/bash

source $HOME/.themes/statusbar_colors.sh

ICON=
BAR_BG_COLOR="^b"$DARK_BACKGROUND"^"
BG_COLOR="^b"$RED_DARK"^"
TEXT_COLOR="^c"$DARK_BACKGROUND"^"
ICON_BG_COLOR="^b"$RED_DARK"^"
ICON_COLOR="^c"$DARK_BACKGROUND"^"
POWERLINE_COLOR="^c"$RED_DARK"^"
POWERLINE_COLOR_2="^c"$RED_LIGHT"^"
LEFT_ARROW='\ue0b2'
LEFT_ROUND='\ue0b6'
RIGHT_ROUND='\ue0b4'


echo -e  $POWERLINE_COLOR$LEFT_ROUND$ICON_BG_COLOR$ICON_COLOR$ICON$BG_COLOR$TEXT_COLOR "$(date '+%R')" $BAR_BG_COLOR$POWERLINE_COLOR$RIGHT_ROUND
