#!/bin/sh

autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:*' enable git
#zstyle ':vcs_info:git*' formats '%F{yellow}(%b)%r%f'
zstyle ':vcs_info:git*' formats  '%F{cyan}(%f%F{red}%m%u%c%f%F{yellow}%f %F{magenta}%b%f%F{cyan})'

#PS1='%F{yellow}%n%f%F{red}@%f%F{blue}%m%f %1~ %F{red} %f '
RPROMPT=\$vcs_info_msg_0_
PROMPT=' %F{blue}%1~%f %F{red} %f ' 
