#!/bin/sh

autoload -Uz vcs_info
autoload -U colors && colors

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
zstyle ':vcs_info:git*' formats  '%F{blue}(%f%F{red}%m%u%c%f%F{yellow}%f %F{magenta}%b%f%F{blue})'

precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

+vi-git-untracked() {
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='!'
    fi
}

#PS1='%F{yellow}%n%f%F{red}@%f%F{blue}%m%f %1~ %F{red} %f '
RPROMPT=\$vcs_info_msg_0_
PROMPT=' %F{blue}%1~%f %F{red} %f ' 
