#!/bin/bash

# Template for modifying a matched string in each file in a directory 

for file in *; do 
    if [ -f "$file" ]; then
        echo "Processing "$file""
        sed -i 's/#!\/bin\/sh/#!\/bin\/bash/g' "$file"
    fi
done
